In [7]:
import numpy as np

In [23]:
#membuat tensor
Tensor=np.array([
                 [[[25,50],[7,12]]],[[[57,67],[99,43]]],
                 [[[75,21],[57,21]]],[[[87,26],[18,84]]]])
print(Tensor)

[[[[25 50]
   [ 7 12]]]


 [[[57 67]
   [99 43]]]


 [[[75 21]
   [57 21]]]


 [[[87 26]
   [18 84]]]]


In [27]:
matrx_a = np.array([[25,50,19],
                   [7,12,109],
                   [57,67,98]])
matrx_b = np.array([[[17],
                    [22],
                    [19]]])
print(matrx_a)
print(matrx_b)

[[ 25  50  19]
 [  7  12 109]
 [ 57  67  98]]
[[[17]
  [22]
  [19]]]


In [22]:
#perkalian matrix
print(matrx_a@matrx_b)

[[[1886]
  [2454]
  [4305]]]


In [29]:
matrx_a

array([[ 25,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [28]:
#Transpose
print(matrx_a)
print('transpose:\n',matrx_a.T)

[[ 25  50  19]
 [  7  12 109]
 [ 57  67  98]]
transpose:
 [[ 25   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [30]:
#Determinant

print(np.linalg.det(matrx_a))

119090.0


In [33]:
#Inverse Matriks

print(np.linalg.inv(matrx_a))

[[-0.05144848 -0.03045596  0.04384919]
 [ 0.04641028  0.01147871 -0.02176505]
 [-0.00180536  0.00986649 -0.00041985]]
